src/objects/Dynamic_Flow_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Lightning_Bundle__c</fullName>
        <label>Lightning Bundle</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Flow Type</label>
    <pluralLabel>Dynamic Flow Types</pluralLabel>
</CustomObject>

src/objects/Flow__c.object
<CustomObject>
    <fields>
        <fullName>Start_Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A questionnaire must have a start page in order for a lead to be assigned to it.</inlineHelpText>
        <label>Start Page</label>
        <referenceTo>FlowPage__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Flows_With_Start_Page</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlowPage__c.object
<CustomObject>
    <fields>
        <fullName>Flow_Page_Key__c</fullName>
        <label>Questionnaire Page Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flow__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Flow__c</referenceTo>
        <relationshipLabel>Questionnaire Pages</relationshipLabel>
        <relationshipName>Flow_Pages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipName>Flow_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NextPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Page</label>
        <referenceTo>FlowPage__c</referenceTo>
        <relationshipName>Linked_Next_Page</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrevPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PrevPage</label>
        <referenceTo>FlowPage__c</referenceTo>
        <relationshipName>Linked_Prev_Page</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Page</label>
    <nameField>
        <label>Questionnaire Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Pages</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DynamicFlowMetadata.cls
public with sharing class DynamicFlowMetadata {

public class FlowPage {
	public FlowPage(FlowPage__c flowPage, Map<String, Dynamic_Flow_Type__mdt> flowTypeMap){
		this.key = flowPage.Flow_Page_Key__c;
		this.type = flowPage.RecordType.Name;
		this.component = flowTypeMap.get(flowPage.RecordType.Name).Lightning_Bundle__c;
		this.componentAttributes = new Map<String, String>();
		this.nextPageKey = flowPage.NextPage__r.Flow_Page_Key__c;
		this.prevPageKey = flowPage.PrevPage__r.Flow_Page_Key__c;
		if(this.type == 'Form'){
			componentAttributes.put('formId', flowPage.Form__c);
		}
	}

	@AuraEnabled
	public String key;

	@AuraEnabled
	public String component;

	@AuraEnabled
	public String type;
	@AuraEnabled
	public String nextPageKey;
	@AuraEnabled
	public String prevPageKey;

	@AuraEnabled
	public Map<String, String> componentAttributes;

}

private Map<String, Dynamic_Flow_Type__mdt> getFlowPageTypes(){
	Dynamic_Flow_Type__mdt[] flowTypeList = [SELECT MasterLabel, DeveloperName, QualifiedApiName, Lightning_Bundle__c FROM Dynamic_Flow_Type__mdt LIMIT 500];
	Map<String, Dynamic_Flow_Type__mdt> flowMap = new Map<String, Dynamic_Flow_Type__mdt>();
	for(Dynamic_Flow_Type__mdt flowType : flowTypeList){
		flowMap.put(flowType.DeveloperName, flowType);
	}
	return  flowMap;
}

public DynamicFlowMetadata(Flow__c flow, List<FlowPage__c> xFlowPages){
	this.startPageKey = flow.Start_Page__r.Flow_Page_Key__c;
	this.flowPages = new List<FlowPage>();
	Map<String, Dynamic_Flow_Type__mdt> flowTypeMap = getFlowPageTypes();
	for(FlowPage__c flowPage : xFlowPages){
		flowPages.add(new FlowPage(flowPage, flowTypeMap));
	}

}

@AuraEnabled
public String flowId;

@AuraEnabled
public Boolean isComplete;

@AuraEnabled
public String startPageKey;

@AuraEnabled
public Boolean validateEmail;

@AuraEnabled
public List<FlowPage> flowPages;
	
}