src/objects/Flow_Data__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Questionnaire Data</label>
    <nameField>
        <displayFormat>FLD-{0000}</displayFormat>
        <label>Questionnaire Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Control__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Label__c</fullName>
        <inlineHelpText>First create a Custom Label in Setup&gt;&gt;Custom Labels. Then input the Name of the previously created custom label.</inlineHelpText>
        <label>Custom Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Embedded Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipName>Form_Control1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form Section</label>
        <referenceTo>Form_Section__c</referenceTo>
        <relationshipName>Form_Control</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipName>Form_Control</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Static_Text__c</fullName>
        <label>Static Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Name</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                    <label>Embedded Form</label>
                </value>
                <value>
                    <fullName>Toggle</fullName>
                </value>
                <value>
                    <fullName>Toggle Multiple</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Static Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Values__c</fullName>
        <description>Comma-separated values used in control types where values need to be specified.</description>
        <inlineHelpText>Comma-separated values used in control types where values need to be specified.</inlineHelpText>
        <label>Values</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Input</label>
    <nameField>
        <label>Form Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Inputs</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <description>Allows users to inset a previously created form into a section of another form.</description>
        <label>Embedded Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Name</fullName>
        <active>true</active>
        <description>Allows users to enter a first name, last name or both</description>
        <label>Name</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form_Data__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Flow_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flow Data</label>
        <referenceTo>Flow_Data__c</referenceTo>
        <relationshipLabel>Form Data</relationshipLabel>
        <relationshipName>Form_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Data</relationshipLabel>
        <relationshipName>Form_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Form Data</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Section__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Label__c</fullName>
        <description>First create a Custom Label in Setup&gt;&gt;Custom Labels. Then input the Name of the previously created custom label.</description>
        <label>Custom Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Sections</relationshipLabel>
        <relationshipName>Form_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FormDataController.cls
public with sharing class FormDataController {

    @AuraEnabled
    public static SaveResponse saveFormApex(Id formId, Id formDataId, Id flowDataId, String formData){
        SaveResponse resp = new SaveResponse();

        List<String> formDataFields = new List<String>{'Form__c', 'Data__c', 'Flow_Data__c'};

        if(!hasFieldAccess('Form_Data__c', formDataFields, true)){
            throw new AuraHandledException('Insufficient Profile Access');
            resp.status = 'error';
            resp.statusMessage = 'Insufficient Profile Access';
            return resp;
        }

        try{
            resp.status = 'success';
            Form_Data__c fd = new Form_Data__c();
            fd.Data__c = formData;
            if(formDataId != null){
                fd.Id = formDataId;
            }
            if(formId != null){
                fd.Form__c = formId;
            }
            if(flowDataId != null){
                fd.Flow_Data__c = flowDataId;
            }
            upsert fd;
            resp.formDataId = fd.Id;

        } catch(Exception e){
            resp.status = 'error';
            resp.statusMessage = e.getMessage();
            System.debug(LoggingLevel.ERROR, e);
        }
        return resp;
    }

    @AuraEnabled
    public static FormObject getFormApex(Id formId, Id formDataId){

        System.debug('FormId ' + formId);
        System.debug('Form Data Id ' + formDataId);
        FormObject fo = new FormObject();
        if(formDataId == null && formId == null){
            System.debug('Returned Null');
            return null;
        }

        //Check field access

        List<String> formDataFields = new List<String>{'Form__c', 'Data__c', 'Flow_Data__c', 'Form__c', 'Read_Only__c'};
        List<String> formSectionFields = new List<String>{'Name', 'Custom_Label__c'};
        List<String> formControlFields = new List<String>{'Name', 'Label__c', 'Required__c', 'Type__c', 'Form__c', 'Form_Lookup__c', 'Values__c', 'Static_Text__c', 'Custom_Label__c', 'Weight__c'};

        if (!hasFieldAccess('Form_Data__c', formDataFields, false) ||
            !hasFieldAccess('Form_Control__c', formControlFields, false) ||
            !hasFieldAccess('Form_Section__c', formSectionFields, false)){
            throw new AuraHandledException('Insufficient Profile Access');
            return null;
        }
        if(formDataId != null){
            for(Form_Data__c fd : [SELECT Data__c, Form__c, Form__r.Name, Email__c, Read_Only__c FROM Form_Data__c WHERE Id = : formDataId]){
                if(formId == null){
                    System.debug('Set form id to : ' + fd.Form__c);
                    formId = fd.Form__c;
                }
                if(fd.Data__c == null){
                    fd.Data__c = '{}';
                }
                fo.formData = fd;
            }
        }
        for(Form_Section__c fs : [SELECT Name, Custom_Label__c, (SELECT Id, Name, Label__c, Required__c, Type__c, Form__c, Form_Lookup__c, Values__c, Static_Text__c, Custom_Label__c  FROM Form_Control__r Order By Weight__c) from Form_Section__c WHERE Form__c = : formId Order By Weight__c]){
            fo.formSections.add(fs);
        }
        system.debug(fo);
        return fo;
    }

    private static Boolean hasFieldAccess(String objectName, List<String> fields, Boolean isUpsert){
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType sobjType = gd.get(objectName);
        Schema.DescribeSObjectResult r = sobjType.getDescribe();
        Map<String,Schema.SObjectField> m = r.fields.getMap();

        Set<String> nonPrefixFields = new Set<String>{'Name', 'RecordType.Name'};

        for(String s : fields){
            if(isUpsert){
                if (m.get(s) != null && (!m.get(s).getDescribe().isUpdateable() || !m.get(s).getDescribe().isCreateable())) {
                    return false;
                }
            }
            else{
                if (m.get(s) != null && !m.get(s).getDescribe().isAccessible()) {
                    return false;
                }
            }
        }
        return true;
    }

    @TestVisible
    private Class SaveResponse{
        @AuraEnabled
        public Id formDataId;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String statusMessage;
    }

    @TestVisible
    private Class FormObject{
        @AuraEnabled
        public Form_Data__c formData = new Form_Data__c();
        @AuraEnabled
        public List<Form_Section__c> formSections = new List<Form_Section__c>();
    }
}