src/objects/Flow__c.object
<CustomObject>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Select the Community that this flow is associated to.  You can find your community URL by going to Setup&gt;&gt;All Communities .  Copy/Paste the URL from the appropriate community.</description>
        <inlineHelpText>Select the Community that this flow is associated to.  You can find your community URL by going to Setup&gt;&gt;All Communities .  Copy/Paste the URL from the appropriate community.</inlineHelpText>
        <label>Community URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flow_Data__c.object
<CustomObject>
    <fields>
        <fullName>Flow__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flow</label>
        <referenceTo>Flow__c</referenceTo>
        <relationshipName>Flow_Data</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Data</label>
    <nameField>
        <displayFormat>FLD-{0000}</displayFormat>
        <label>Questionnaire Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlowPage__c.object
<CustomObject>
    <fields>
        <fullName>Flow_Page_Key__c</fullName>
        <label>Questionnaire Page Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flow__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Flow__c</referenceTo>
        <relationshipLabel>Questionnaire Pages</relationshipLabel>
        <relationshipName>Flow_Pages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipName>Flow_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Page</label>
    <nameField>
        <label>Questionnaire Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Control__c.object
<CustomObject>
    <fields>
        <fullName>Form_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form Section</label>
        <referenceTo>Form_Section__c</referenceTo>
        <relationshipName>Form_Control</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipName>Form_Control</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Name</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                    <label>Embedded Form</label>
                </value>
                <value>
                    <fullName>Toggle</fullName>
                </value>
                <value>
                    <fullName>Toggle Multiple</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Static Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Input</label>
    <nameField>
        <label>Form Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Inputs</pluralLabel>
    <recordTypes>
        <fullName>Name</fullName>
        <active>true</active>
        <description>Allows users to enter a first name, last name or both</description>
        <label>Name</label>
    </recordTypes>
    <recordTypes>
        <fullName>Text</fullName>
        <active>true</active>
        <description>Allows users to enter a text string</description>
        <label>Text</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form_Data__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Flow_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flow Data</label>
        <referenceTo>Flow_Data__c</referenceTo>
        <relationshipLabel>Form Data</relationshipLabel>
        <relationshipName>Form_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Data</relationshipLabel>
        <relationshipName>Form_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Form Data</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Section__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Sections</relationshipLabel>
        <relationshipName>Form_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FormDataControllerTest.cls
@IsTest
private with sharing class FormDataControllerTest {

    private static Flow__c thisFlow;
    private static Form__c thisForm;
    private static Flow_Data__c thisFlowData;
    private static Form_Data__c thisFormData;
    private static Form_Control__c thisControl;

    static{

        thisFlow = new Flow__c();
        thisFlow.Community_URL__c = 'testurl';
        insert thisFlow;

        thisForm = new Form__c();
        thisForm.Version__c = 1;
        insert thisForm;

        FlowPage__c thisFlowPage = new FlowPage__c();
        thisFlowPage.Flow__c = thisFlow.Id;
        thisFlowPage.Form__c = thisForm.Id;
        thisFlowPage.Flow_Page_Key__c = 'this-flow-page';
        insert thisFlowPage;

        Form_Section__c thisSection = new Form_Section__c();
        thisSection.Name = 'Test Section';
        thisSection.Form__c = thisForm.Id;
        insert thisSection;

        thisControl = new Form_Control__c();
        thisControl.Form__c = thisForm.Id;
        thisControl.Form_Section__c = thisSection.Id;
        thisControl.Label__c = 'My Label';
        thisControl.Type__c = 'Text';
        insert thisControl;

        thisFlowData = new Flow_Data__c();
        thisFlowData.Flow__c = thisFlow.Id;
        insert thisFlowData;

        thisFormData = new Form_Data__c();
        thisFormData.Form__c = thisForm.Id;
        insert thisFormData;
    }

    static testMethod void testSaveFormApex(){
        String formData = '{"' + thisControl.Id + '" : "My Test Value"}';
        FormDataController.SaveResponse resp = FormDataController.saveFormApex(thisForm.Id, thisFormData.Id, thisFlowData.Id, formData);

        //Assert call completed successfully.
        System.assertEquals('success', resp.status);
        System.assertEquals(thisFormData.Id, resp.formDataId);

        //Assert data was saved.
        List<Form_Data__c> queriedFormData = [SELECT Data__c FROM Form_Data__c WHERE Id = : thisFormData.Id LIMIT 1];
        System.assertEquals(true, queriedFormData[0].Data__c.contains('My Test Value'));
    }

    static testMethod void testSaveFormApexException(){
        String formData = '{"' + thisControl.Id + '" : "My Test Value"}';
        //Pass an invalid Id for the flowData to generate exception (thisFlow vs thisFlowData).
        FormDataController.SaveResponse resp = FormDataController.saveFormApex(thisForm.Id, thisFormData.Id, thisFlow.Id, formData);

        //Assert call failed.
        System.assertEquals('error', resp.status);
    }

    static testMethod void testGetFormApex(){
        FormDataController.FormObject resp = FormDataController.getFormApex(thisForm.Id, thisFormData.Id);

        //Assert formdata and sections are returned.
        System.assertEquals(thisFormData.Id, resp.FormData.Id);
        System.assertEquals(1, resp.formSections.size());
    }
    static testMethod void testGetFormApexWithoutFormId(){
        FormDataController.FormObject resp = FormDataController.getFormApex(null, thisFormData.Id);

        //Assert formdata and sections are returned.
        System.assertEquals(thisFormData.Id, resp.FormData.Id);
        System.assertEquals(1, resp.formSections.size());
    }
    static testMethod void testGetFormApexWithNoIds(){
        FormDataController.FormObject resp = FormDataController.getFormApex(null, null);

        //Assert null response
        System.assertEquals(null, resp);
    }
}