src/objects/Flow_Data__c.object
<CustomObject>
    <fields>
        <fullName>PageData__c</fullName>
        <description>Page Data</description>
        <label>PageData</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                    <default>true</default>
                    <label>Ready</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validate_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validate Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Questionnaire Data</label>
    <nameField>
        <displayFormat>FLD-{0000}</displayFormat>
        <label>Questionnaire Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DynamicFlowInstance.cls
public with sharing class DynamicFlowInstance {
	public DynamicFlowInstance(DynamicFlowMetadata flowMetadata, Flow_Data__c flowData) {
		this.flowMetadata = flowMetadata;
		this.flowMetadata.flowId = flowData.Id;
		this.flowMetadata.isComplete = flowData.Status__c == 'Complete';
		this.flowMetadata.validateEmail = flowData.Validate_Email__c;
		this.pageData = flowData.PageData__c;
	}

	@AuraEnabled
	public DynamicFlowMetadata flowMetadata;


	@AuraEnabled
	public String pageData;
	
}